
#### general settings
name: 001_Corrector_Div2K
use_tb_logger: true
model: corrector
distortion: sr
scale: 4
gpu_ids: [0,1,2]
step: 8
kernel_size: 21
code_length: 10
sig_min: 0.2
sig_max: 4.0
sig: 2.6

#### datasets
datasets:
  train:
    name: Div2K
    mode: Normal
    dataroot_GT: HR/Train_HR
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 2
    GT_size: 512
    LR_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Div2K
    mode: Normal
    dataroot_GT: HR/Val_HR
    dataroot_LQ: ~

#### network structures
network_G:
  which_model_G: Corrector
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 4
  code_length: 10

#### path
path:
  pretrain_model_G: fine tuned corrector weights path
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: ~
  beta1: 0.9
  beta2: 0.99
  niter: 50000
  warmup_iter: -1  # no warm up
  T_period: ~ #[250000, 250000, 250000, 250000]
  restarts: ~ #[250000, 500000, 750000]
  restart_weights: ~ #[1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: 450 #!!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 450
